name: KAN-2Hidden
model:
  _target_: kan.KAN
  width:
    - ${train.feature_size}
    - 5
    - 5
    - ${label_transforms.n_classes}
  grid: 3
  k: 3
  device: ${device}
  seed: 0
  symbolic_enabled: true

train_params:
  opt: Adam
  steps: 20000
  device: ${device}
  lamb: 0
  lamb_l1: 0.2
  lamb_entropy: 0.2
  lr: 1e-3
  batch: 256
  loss_fn: ${label_transforms.loss_fn}
