name: KAN-2Hidden
plot_graph: false
model:
  _target_: kan.KAN
  width:
    - ${train.trace_len}
    - 5
    - 5
    - ${label_transforms.n_classes}
  grid: 3
  k: 3
  device: ${device}
  seed: 0
  symbolic_enabled: true

train_params:
  opt: Adam
  steps: 20000
  device: ${device}
  lamb: 0
  lamb_l1: 0.2
  lamb_entropy: 0.2
  lr: 1e-3
  batch: 256
  loss_fn:
    _target_: torch.nn.CrossEntropyLoss
