name: MLP
model:
  _target_: src.dnn.from_yaml
  layers:
    - _target_: torch.nn.LazyLinear
      out_features: 32
    - _target_: torch.nn.ReLU
    - _target_: torch.nn.LazyLinear
      out_features: ${label_transforms.n_classes}

train_params:
  opt:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 1e-3
  steps: 20000
  device: ${device}
  batch: 256
  loss_fn: ${label_transforms.loss_fn}
