trace_len: 4
feature_size: ${trace_transforms.output_size}
batch_size: 2048
dataset:
  _target_: src.datasets.ASCAD_sim.RandomDataset
  n_traces: 50000
  target_byte: ${target_byte}
  sigma: 0.1
  trace_transforms: ${trace_transforms.transforms}
  label_transforms: ${label_transforms.transforms}