n_classes: 1
one_hot: false
transforms:
  - _target_: src.aes_utils.ignore_mask
  - _target_: src.aes_utils.apply_target_byte
    target_byte: ${target_byte}
  - _target_: src.aes_utils.calc_iv
  - _target_: src.sca_utils.calc_bit
    pos: 0
  - _target_: src.utils.to_torch
    _partial_: true
  - _target_: src.utils.to_float
    _partial_: true
  - _target_: torch.unsqueeze
    _partial_: true
    dim: -1
loss_fn:
  _target_: torch.nn.BCEWithLogitsLoss