n_classes: 256
dtype: int64
transforms:
  - _target_: src.aes_utils.ignore_mask
  - _target_: src.aes_utils.apply_target_byte
    target_byte: ${target_byte}
  - _target_: src.aes_utils.calc_iv
loss_fn:
  _target_: torch.nn.CrossEntropyLoss