n_classes: 8
one_hot: false
target_snr: 2
transforms:
  - _target_: src.aes_utils.calc_snr
    target_byte: ${target_byte}
    target_snr: ${label_transforms.target_snr}
  - _target_: src.sca_utils.calc_multilabel
  - _target_: src.utils.to_torch
    _partial_: true
  - _target_: src.utils.to_float
    _partial_: true
loss_fn:
  _target_: torch.nn.BCELoss