# UNDER CONSTRUCTION: DO NOT USE
n_classes: 8
one_hot: false
transforms:
  - _target_: src.aes_utils.ignore_mask
  - _target_: src.aes_utils.apply_target_byte
    target_byte: ${target_byte}
  - _target_: src.aes_utils.calc_iv
  - _target_: src.sca_utils.calc_multilabel
    _partial_: true
  - _target_: src.utils.to_torch
    _partial_: true
  - _target_: src.utils.to_float
    _partial_: true
loss_fn:
  _target_: torch.nn.BCELoss
